name: Spik
version: 1.0.0
author: Symbiosis
main: be.symbiosis.spik.Spik
depend: [Citizens]
commands:
  target:
    description: Cette commande permet de lancer une animation aléatoire
  anim:
    description: Permet de mettre une position au animation
  cuboid:
    description: Permet de niquer ta mère
api-version: 1.16